/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AgentRouteImport } from './routes/agent'
import { Route as TabsRouteImport } from './routes/_tabs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PropertyIdRouteImport } from './routes/property.$id'
import { Route as TabsProfileRouteImport } from './routes/_tabs.profile'
import { Route as TabsInteressesRouteImport } from './routes/_tabs.interesses'
import { Route as TabsExploreRouteImport } from './routes/_tabs.explore'
import { Route as TabsAlertasRouteImport } from './routes/_tabs.alertas'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentRoute = AgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const TabsRoute = TabsRouteImport.update({
  id: '/_tabs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertyIdRoute = PropertyIdRouteImport.update({
  id: '/property/$id',
  path: '/property/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TabsProfileRoute = TabsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => TabsRoute,
} as any)
const TabsInteressesRoute = TabsInteressesRouteImport.update({
  id: '/interesses',
  path: '/interesses',
  getParentRoute: () => TabsRoute,
} as any)
const TabsExploreRoute = TabsExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => TabsRoute,
} as any)
const TabsAlertasRoute = TabsAlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => TabsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agent': typeof AgentRoute
  '/onboarding': typeof OnboardingRoute
  '/alertas': typeof TabsAlertasRoute
  '/explore': typeof TabsExploreRoute
  '/interesses': typeof TabsInteressesRoute
  '/profile': typeof TabsProfileRoute
  '/property/$id': typeof PropertyIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agent': typeof AgentRoute
  '/onboarding': typeof OnboardingRoute
  '/alertas': typeof TabsAlertasRoute
  '/explore': typeof TabsExploreRoute
  '/interesses': typeof TabsInteressesRoute
  '/profile': typeof TabsProfileRoute
  '/property/$id': typeof PropertyIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_tabs': typeof TabsRouteWithChildren
  '/agent': typeof AgentRoute
  '/onboarding': typeof OnboardingRoute
  '/_tabs/alertas': typeof TabsAlertasRoute
  '/_tabs/explore': typeof TabsExploreRoute
  '/_tabs/interesses': typeof TabsInteressesRoute
  '/_tabs/profile': typeof TabsProfileRoute
  '/property/$id': typeof PropertyIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agent'
    | '/onboarding'
    | '/alertas'
    | '/explore'
    | '/interesses'
    | '/profile'
    | '/property/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agent'
    | '/onboarding'
    | '/alertas'
    | '/explore'
    | '/interesses'
    | '/profile'
    | '/property/$id'
  id:
    | '__root__'
    | '/'
    | '/_tabs'
    | '/agent'
    | '/onboarding'
    | '/_tabs/alertas'
    | '/_tabs/explore'
    | '/_tabs/interesses'
    | '/_tabs/profile'
    | '/property/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TabsRoute: typeof TabsRouteWithChildren
  AgentRoute: typeof AgentRoute
  OnboardingRoute: typeof OnboardingRoute
  PropertyIdRoute: typeof PropertyIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent': {
      id: '/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_tabs': {
      id: '/_tabs'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof TabsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/property/$id': {
      id: '/property/$id'
      path: '/property/$id'
      fullPath: '/property/$id'
      preLoaderRoute: typeof PropertyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_tabs/profile': {
      id: '/_tabs/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof TabsProfileRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/interesses': {
      id: '/_tabs/interesses'
      path: '/interesses'
      fullPath: '/interesses'
      preLoaderRoute: typeof TabsInteressesRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/explore': {
      id: '/_tabs/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof TabsExploreRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/alertas': {
      id: '/_tabs/alertas'
      path: '/alertas'
      fullPath: '/alertas'
      preLoaderRoute: typeof TabsAlertasRouteImport
      parentRoute: typeof TabsRoute
    }
  }
}

interface TabsRouteChildren {
  TabsAlertasRoute: typeof TabsAlertasRoute
  TabsExploreRoute: typeof TabsExploreRoute
  TabsInteressesRoute: typeof TabsInteressesRoute
  TabsProfileRoute: typeof TabsProfileRoute
}

const TabsRouteChildren: TabsRouteChildren = {
  TabsAlertasRoute: TabsAlertasRoute,
  TabsExploreRoute: TabsExploreRoute,
  TabsInteressesRoute: TabsInteressesRoute,
  TabsProfileRoute: TabsProfileRoute,
}

const TabsRouteWithChildren = TabsRoute._addFileChildren(TabsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TabsRoute: TabsRouteWithChildren,
  AgentRoute: AgentRoute,
  OnboardingRoute: OnboardingRoute,
  PropertyIdRoute: PropertyIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
