export enum HttpStatusEnum {
    OK = 200,
    CREATED = 201,
    UNPROCESSABLE_ENTITY = 422,
    TOO_MANY_REQUESTS = 429,
    INTERNAL_SERVER_ERROR = 500,
    INVALID_CREDENTIALS = 400,
    UNAUTHORIZED = 401,
}